version: "3.8"
services:
  stock_watcher_server:
    build: 
      context: ./server
      dockerfile: $PWD/Dockerfile
    container_name: stock_watcher_server
    env_file:
      - ./server/app.env
    environment:
      PORT: ${APP_PORT}
    depends_on: 
      - stock_watcher_mongo
    networks:
      - stock_watcher_network
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./server:/home/stock_watcher_server
    tty: true
    working_dir: /home/stock_watcher_server
  stock_watcher_mongo:
    image: mongo
    container_name: stock_watcher_mongo
    networks:
      - stock_watcher_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - stock_watcher-mongo-data:/data/db
  stock_watcher_mongo_express:
    image: mongo-express
    container_name: stock_watcher_mongo_express
    networks:
      - stock_watcher_network
    depends_on: 
      - stock_watcher_mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: stock_watcher_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@stock_watcher_mongo:27017/
    volumes:
      - stock_watcher-mongo-data:/data/db
networks:
  stock_watcher_network:
    driver: bridge
volumes:
  stock_watcher-mongo-data: